#!/usr/bin/env bash

export C2J_DEV_POSTGRES_PORT=5432
export C2J_DEV_POSTGRES_USER=csv2json
export C2J_DEV_POSTGRES_PASSWORD=password
export C2J_DEV_POSTGRES_DATABASE=csv2json

export DATABASE_URL="postgres://${C2J_DEV_POSTGRES_USER}:${C2J_DEV_POSTGRES_PASSWORD}@localhost:5432/${C2J_DEV_POSTGRES_DATABASE}"
